import 'package:flutter/material.dart';

class CostosPage extends StatelessWidget {
  const CostosPage({super.key});

  final List<Map<String, String>> costos = const [
    {
      'clave': 'PRE013',
      'concepto': 'MOVILIZACION DE MAQUINARIAS HERRAMIENTAS PARA LA OBRA',
      'unidad': 'est',
      'cantidad': '198',
      'pu': '\$414,011.41',
      'importe': '\$81,974,259.18',
    },
    {
      'clave': 'PRE014',
      'concepto': 'TOPOGRAFIA Y GEOREFERENCIACION',
      'unidad': 'km',
      'cantidad': '13.8',
      'pu': '\$1,169.13',
      'importe': '\$16,133.99',
    },
    {
      'clave': 'PRE015',
      'concepto': 'MANTENIMIENTO DE TRANSITO Y SEGURIDAD VIAL',
      'unidad': 'km',
      'cantidad': '13.8',
      'pu': '\$39,956.06',
      'importe': '\$551,393.63',
    },
    {
      'clave': 'PRE016',
      'concepto': 'ACCESOS A CANTERAS, DME, PLANTAS Y FUENTES DE AGUA',
      'unidad': 'km',
      'cantidad': '13.8',
      'pu': '\$39,956.06',
      'importe': '\$551,393.63',
    },
    {
      'clave': 'PRE016',
      'concepto': 'ACCESOS A CANTERAS, DME, PLANTAS Y FUENTES DE AGUA (2)',
      'unidad': 'km',
      'cantidad': '13.8',
      'pu': '\$24,265.76',
      'importe': '\$334,867.49',
    },
    {
      'clave': 'PRE017',
      'concepto': 'trazo y nivelación con equipo topográfico, estableciendo ejes de referencia y bancos de nivel, incluye materiales, mano de obra equipo y herramienta (hasta 500m2)',
      'unidad': 'M2',
      'cantidad': '198',
      'pu': '\$70.88',
      'importe': '\$14,034.24',
    },
    {
      'clave': 'PRE018',
      'concepto': 'Limpia y desyerbe del terreno, incluye: quema de yerba, y acopio de basura, mano de obra, equipo y herramienta',
      'unidad': 'M2',
      'cantidad': '198',
      'pu': '\$65.66',
      'importe': '\$13,000.68',
    },
     {
      'clave': 'EXC001',
      'concepto': 'EXCAVACIÓN EN CORTES DE 50 CM DE ESPESOR EN REBAJES EN LA CORONA EN CORTES O TERRAPLENES EXISTENTES P.U.O.T. EN MATERIAL B CUANDO EL MATERIAL SE DESPERDICIE',
      'unidad': 'M3',
      'cantidad': '200000',
      'pu': '\$161.31',
      'importe': '\$3,266,200.00',
    },
    {
      'clave': 'EX002',
      'concepto': 'EXCAVACIÓN DE ZANJAS PARA OBRAS DE DRENAJE, INCLUYE ACARREOS DEL MATERIAL PRODUCTO DE LA EXCAVACIÓN A CUALQUIER DISTANCIA AL BANCO DE DESPERDICIO QUE ELIJA EL CONTRATISTA, P.U.O.T.',
      'unidad': 'M3',
      'cantidad': '2000',
      'pu': '\$78.47',
      'importe': '\$156,940.00'
    },
    {
      'clave': 'EX003',
      'concepto': 'ACARREOS DE LOS MATERIALES PRODUCTO DE LAS EXCAVACIONES DE CORTES, ADICIONALES DEBAJO DE LA SUBRASANTE, AMPLIACIÓN Y/O ABATIMIENTO DE TALUDES, REBAJES EN LA CORONA DE CORTES Y/O TERRAPLENES EXISTENTES, ESCALONES, DESPALMES, PRÉSTAMO DE BANCOS, DERRUMBES, CANALES Y DEL AGUA EMPLEADA EN LAS COMPACTACIONES PARA EL PRIMER KILÓMETRO',
      'unidad': 'M3',
      'cantidad': '166.375',
      'pu': '\$17.81',
      'importe': '\$2,963.14'
    },
    {
      'clave': 'EX004',
      'concepto': 'ACARREOS DE LOS MATERIALES PRODUCTO DE LAS EXCAVACIONES DE CORTES, ADICIONALES DEBAJO DE LA SUBRASANTE, AMPLIACIÓN Y/O ABATIMIENTO DE TALUDES, REBAJES EN LA CORONA DE CORTES Y/O TERRAPLENES EXISTENTES, ESCALONES, DESPALMES, PRÉSTAMO DE BANCOS, DERRUMBES, CANALES Y DEL AGUA EMPLEADA EN LAS COMPACTACIONES PARA LOS KILÓMETROS SUBSECUENTES',
      'unidad': 'M3',
      'cantidad': '166.375',
      'pu': '\$9.97',
      'importe': '\$1,658.76'
    },
    {
      'clave': 'EX005',
      'concepto': 'FORMACIÓN Y COMPACTACIÓN DE TERRAPLENES CON SUS CUÑAS DE SOBREANCHO P.U.O.T. (EN EXCAVACIONES DE CORONA), INCLUYE: REGALÍA DE PRÉSTAMO DE BANCO, ACARREO A 50 KM Y TODO LO NECESARIO PARA SU CORRECTA EJECUCIÓN (MATERIAL EN GREÑA DE RIO)',
      'unidad': 'M3',
      'cantidad': '133.1',
      'pu': '\$308.12',
      'importe': '\$41,010.77'
    },
    {
      'clave': 'CIM001',
      'concepto': 'DESORILLAMIENTO DE LA SUPERFICIE DE RODAMIENTO',
      'unidad': 'M',
      'cantidad': '20000',
      'pu': '\$15,533.10',
      'importe': '\$310,662,000.00'
    },
    {
      'clave': 'EYA001',
      'concepto': 'BASE HIDRÁULICA POR UNIDAD DE OBRA TERMINADA, DE 20 CM DE ESPESOR COMPACTO, EL MATERIAL INCLUYE: ADQUISICIÓN, ACARREO A 50 KM, COLOCACIÓN Y TODO LO NECESARIO PARA SU CORRECTA TERMINACIÓN',
      'unidad': 'M3',
      'cantidad': '20000',
      'pu': '\$252.40',
      'importe': '\$5,048,000.00'
    },
    {
      'clave': 'EYA002',
      'concepto': 'BACHEO PROFUNDO POR UNIDAD DE OBRA TERMINADA, COMPACTADO AL 95% DE SU P.V.S.M., INCLUYE ADQUISICIÓN, ACARREO A 50 KM DEL C.G., COLOCACIÓN Y TODO LO NECESARIO PARA SU CORRECTA EJECUCIÓN',
      'unidad': 'm2',
      'cantidad': '345.27',
      'pu': '\$6.25',
      'importe': '\$2,157.94',
    },
    {
      'clave': 'EYA003',
      'concepto': 'BACHEO SUPERFICIAL',
      'unidad': 'm2',
      'cantidad': '2000',
      'pu': '\$59.16',
      'importe': '\$118,320.00',
    },
    {
      'clave': 'EYA004',
      'concepto': 'RIEGO DE LIGA',
      'unidad': 'm2',
      'cantidad': '2000',
      'pu': '\$0.52',
      'importe': '\$1,040.00',
    },
    {
      'clave': 'EYA005',
      'concepto': 'EMULSIÓN ASFÁLTICA DE ROTURA LENTA',
      'unidad': 'L',
      'cantidad': '10000',
      'pu': '\$2.29',
      'importe': '\$22,900.00',
    },
    {
      'clave': 'EYA006',
      'concepto': 'RECAPADO ASFÁLTICO',
      'unidad': 'm3',
      'cantidad': '5000',
      'pu': '\$122.35',
      'importe': '\$611,750.00',
    },
    {
      'clave': 'EYA007',
      'concepto': 'CONSTRUCCIÓN DE CUNETA A BASE DE CONCRETO F\'C=150 KG/CM², DE 10 CM DE ESPESOR Y CARACTERÍSTICAS SEGÚN PROYECTO, P.U.O.T.',
      'unidad': 'm',
      'cantidad': '20000',
      'pu': '\$228.06',
      'importe': '\$4,561,200.00',
    },
    {
      'clave': 'EYA008',
      'concepto': 'CONSTRUCCIÓN DE LAVADERO DE F´C= 150 KG/CM2 EP 1.02.003/04. E.01B',
      'unidad': 'm3',
      'cantidad': '2000',
      'pu': '\$252.26',
      'importe': '\$504,520.00',
    },
    {
      'clave': 'EYA009',
      'concepto': 'BORDILLO DE F´C= 150 KG/CM2, DE 15 CM BASE MAYOR, 8 CM BASE MENOR Y 12 CM ALTURA',
      'unidad': 'm',
      'cantidad': '20000',
      'pu': '\$98.18',
      'importe': '\$1,963,600.00',
    },
    {
      'clave': 'EYA010',
      'concepto': 'RAYA CENTRAL CONTINUA/DISCONTINUA BLANCA, DE 15 CM CON MICROESFERA',
      'unidad': 'm',
      'cantidad': '20000',
      'pu': '\$30.19',
      'importe': '\$603,800.00',
    },
    {
      'clave': 'EYA011',
      'concepto': 'RAYA LATERAL CONTINUA AMARILLA, DE 15 CM CON MICROESFERA',
      'unidad': 'm',
      'cantidad': '20000',
      'pu': '\$30.19',
      'importe': '\$603,800.00',
    },
    {
      'clave': 'EYA012',
      'concepto': 'FRESADO DE CARPETA ASFÁLTICA E=2.5 CM',
      'unidad': 'm2',
      'cantidad': '5000',
      'pu': '\$3.74',
      'importe': '\$18,700.00',
    },
    {
      'clave': 'EYA013',
      'concepto': 'SEÑALAMIENTO VERTICAL SP-6 CURVA: 61 X 61 CM',
      'unidad': 'pza',
      'cantidad': '10',
      'pu': '\$1,721.35',
      'importe': '\$17,213.50',
    },
    {
      'clave': 'EYA014',
      'concepto': 'SEÑALAMIENTO VERTICAL SP-23 PUENTE ANGOSTO: 61 X 61 CM',
      'unidad': 'pza',
      'cantidad': '10',
      'pu': '\$1,721.35',
      'importe': '\$17,213.50',
    },
    {
      'clave': 'EYA015',
      'concepto': 'SEÑALAMIENTO VERTICAL SP-32 PEATONES: 61 X 61 CM',
      'unidad': 'pza',
      'cantidad': '10',
      'pu': '\$1,721.35',
      'importe': '\$17,213.50',
    },
    {
      'clave': 'EYA016',
      'concepto': 'SEÑALES RESTRICTIVAS SR-6 ALTO: 25 CM POR LADO',
      'unidad': 'pza',
      'cantidad': '10',
      'pu': '\$1,721.35',
      'importe': '\$17,213.50',
    },
    {
      'clave': 'EYA017',
      'concepto': 'SEÑALES RESTRICTIVAS SR-9 VELOCIDAD: 61 X 61 CM',
      'unidad': 'pza',
      'cantidad': '10',
      'pu': '\$1,721.35',
      'importe': '\$17,213.50',
    },
    {
      'clave': 'EYA018',
      'concepto': 'SEÑALES RESTRICTIVAS SR-18 PROHIBIDO REBASAR: 61 X 61 CM',
      'unidad': 'pza',
      'cantidad': '10',
      'pu': '\$1,721.35',
      'importe': '\$17,213.50',
    },
    {
      'clave': 'EYA019',
      'concepto': 'SEÑALES INFORMATIVAS SII-15 KILOMETRAJE SIN RUTA, DE 30x76 CM',
      'unidad': 'pza',
      'cantidad': '10',
      'pu': '\$1,721.35',
      'importe': '\$17,213.50',
    },
    {
      'clave': 'EYA020',
      'concepto': 'SEÑAL DE DESTINO SID-8 ACCESO A POBLADO: DE 30 X 178 CM',
      'unidad': 'pza',
      'cantidad': '10',
      'pu': '\$1,721.35',
      'importe': '\$17,213.50',
    },
    {
      'clave': 'EYA021',
      'concepto': 'SEÑALES INDICADORES DE ALINEAMIENTO OD-6 DE 13 CM, FANTASMAS',
      'unidad': 'pza',
      'cantidad': '10',
      'pu': '\$622.31',
      'importe': '\$6,223.10',
    },
    {
    'clave': 'EYA022',
    'concepto': 'Vialetas: Con reflejante en 2 caras, EP 044-E.07 amarillo en ambas caras',
    'unidad': 'pza',
    'cantidad': '10',
    'pu': '\$26.88',
    'importe': '\$268.80',
  },
  {
    'clave': 'EYA023',
    'concepto': 'Vialetas: Con reflejante en 2 caras, EP 044-E.07 blanco en el sentido del tránsito',
    'unidad': 'pza',
    'cantidad': '10',
    'pu': '\$26.88',
    'importe': '\$268.80',
  },
  {
    'clave': 'SAN001',
    'concepto': 'Tubo de PVC sanitario de 50 mm de diámetro',
    'unidad': 'm',
    'cantidad': '20.99',
    'pu': '\$215.64',
    'importe': '\$4,526.28',
  },
  {
    'clave': 'SAN002',
    'concepto': 'Tubo de PVC sanitario de 100 mm de diámetro',
    'unidad': 'm',
    'cantidad': '5.16',
    'pu': '\$176.65',
    'importe': '\$911.51',
  },
  {
    'clave': 'SAN003',
    'concepto': 'Yee reducción de PVC sanitario 100x50 mm',
    'unidad': 'pza',
    'cantidad': '1',
    'pu': '\$193.25',
    'importe': '\$193.25',
  },
  {
    'clave': 'SAN004',
    'concepto': 'Yee de PVC sanitario 102 mm',
    'unidad': 'pza',
    'cantidad': '2',
    'pu': '\$219.93',
    'importe': '\$439.86',
  },
  {
    'clave': 'SAN005',
    'concepto': 'Codo de PVC sanitario 90°x50 mm',
    'unidad': 'pza',
    'cantidad': '5',
    'pu': '\$83.81',
    'importe': '\$419.05',
  },
  {
    'clave': 'INE003',
    'concepto': 'Salida eléctrica para alumbrado (PVC ligero, 13 y 19 mm)',
    'unidad': 'SAL',
    'cantidad': '1',
    'pu': '\$651.02',
    'importe': '\$651.02',
  },
  {
    'clave': 'INE004',
    'concepto': 'Salida eléctrica para contacto (PVC pesado, 13 y 19 mm)',
    'unidad': 'SAL',
    'cantidad': '5',
    'pu': '\$721.39',
    'importe': '\$3,606.95',
  },
  {
    'clave': 'INE005',
    'concepto': 'Tubo conduit de PVC ligero de 19 mm',
    'unidad': 'M',
    'cantidad': '12.19',
    'pu': '\$28.75',
    'importe': '\$350.46',
  },
  {
    'clave': 'INE007',
    'concepto': 'Caja cuadrada de pvc de 3/4" con tapa',
    'unidad': 'PZA',
    'cantidad': '1',
    'pu': '\$56.33',
    'importe': '\$56.33',
  },
  {
    'clave': 'INE008',
    'concepto': 'Interruptor termomagnético FAL 24030, 2P 30A, 480V',
    'unidad': 'PZA',
    'cantidad': '1',
    'pu': '\$5,062.83',
    'importe': '\$5,062.83',
  },
  {
    'clave': 'INE009',
    'concepto': 'Centro de carga QO816L100 con 4 interruptores de 1x15A',
    'unidad': 'PZA',
    'cantidad': '1',
    'pu': '\$2,489.70',
    'importe': '\$2,489.70',
  },
  {
    'clave': 'INE010',
    'concepto': 'Centro de carga QO816L100 versión empotrable con zapatas',
    'unidad': 'PZA',
    'cantidad': '1',
    'pu': '\$42,067.80',
    'importe': '\$42,067.80',
  },
  {
    'clave': 'INE011',
    'concepto': 'Centro de carga QO816L100 con zapatas principales',
    'unidad': 'M',
    'cantidad': '11',
    'pu': '\$1,865.81',
    'importe': '\$20,523.91',
  },
  {
    'clave': 'SAN006',
    'concepto': 'Centro de carga tipo QO con interruptores derivados',
    'unidad': 'pza',
    'cantidad': '1',
    'pu': '\$192.60',
    'importe': '\$192.60',
  },
  {
    'clave': 'TOTAL',
    'importe': '\$412,195,272.90',
  },
  {
    'clave': 'costo directo',
    'importe': '\$412,195,272.90',
  },
  {
    'clave': 'COSTO INDIRECTO (20%)',
    'importe': '\$82,439,054.58',
  },
  {
    'clave': 'FINANCIAMIENTO (3%)',
    'importe': '\$12,365,858.19',
  },
  {
    'clave': 'UTILIDAD (5%)',
    'importe': '\$20,609,763.64',
  },
  {
    'clave': 'PRECIO UNITARIO TOTAL',
    'importe': '\$527,609,949.31',
  },
];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('COSTOS DEL PROYECTO'),
        backgroundColor: Colors.deepPurple,
        centerTitle: true,
      ),
      body: ListView.builder(
        padding: const EdgeInsets.all(16),
        itemCount: costos.length,
        itemBuilder: (context, index) {
          final costo = costos[index];
          return Card(
            margin: const EdgeInsets.symmetric(vertical: 8),
            elevation: 3,
            child: Padding(
              padding: const EdgeInsets.all(12),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    '${costo['clave']} - ${costo['concepto']}',
                    style: const TextStyle(fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 8),
                  Text('Unidad: ${costo['unidad']}'),
                  Text('Cantidad: ${costo['cantidad']}'),
                  Text('Precio Unitario: ${costo['pu']}'),
                  Text('Importe: ${costo['importe']}'),
                ],
              ),
            ),
          );
        },
      ),
    );
  }
}
