// ✅ Este archivo incluye las 65 actividades completas de la sección PERTH
import 'package:flutter/material.dart';

class PerthPage extends StatelessWidget {
  const PerthPage({super.key});

  final List<Map<String, String>> actividades = const [
    { 'nombre': 'Anteproyecto', 
      'predecesoras': '-', 
      'optimo': '3 días', 
      'real': '4 días',
      'estimado': '4.000 días',
      'pesimista': '5 días' },

    { 'nombre': 'Proyecto',
      'predecesoras': '-', 
      'optimo': '5 días', 
      'real': '7 días', 
      'estimado': '7.333 días', 
      'pesimista': '12 días' },

    { 'nombre': 'Trámites administrativos',
      'predecesoras': 'A, B',
      'optimo': '8 días',
      'real': '14 días',
      'estimado': '13.167 días',
      'pesimista': '15 días' },

    { 'nombre': 'Levantamiento topográfico',
      'predecesoras': 'A, B',
      'optimo': '8 días',
      'real': '12 días',
      'estimado': '11.333 días',
      'pesimista': '12 días' },

    { 'nombre': 'Cartel de identificación de obra',
      'predecesoras': 'D, E',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.000 día',
      'pesimista': '1 día' },

    { 'nombre': 'Movilización y desmovilización de equipos',
      'predecesoras': 'E',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.000 día',
      'pesimista': '1 día' },

    { 'nombre': 'Mantenimiento de tránsito y seguridad vial',
      'predecesoras': 'F',
      'optimo': '5 días',
      'real': '6 días',
      'estimado': '5.833 días',
      'pesimista': '6 días' },

    { 'nombre': 'Flete terrestre',
      'predecesoras': 'F',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.167 días',
      'pesimista': '2 días' },

    { 'nombre': 'Fresado de pavimento y desecho del material',
      'predecesoras': 'F, G, H',
      'optimo': '3 días',
      'real': '5 días',
      'estimado': '4.833 días',
      'pesimista': '6 días' },

    { 'nombre': 'Excavación a 2m con motoescrepa',
      'predecesoras': 'I',
      'optimo': '3 días',
      'real': '5 días',
      'estimado': '4.833 días',
      'pesimista': '6 días' },

    { 'nombre': 'Relleno con material propio o de banco de nivel del cuerpo del terraplén',
      'predecesoras': 'J',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '3.000 días',
      'pesimista': '4 días' },

    { 'nombre': 'Compactación del cuerpo del terraplén al 90%',
      'predecesoras': 'K',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.167 día',
      'pesimista': '2 días' },

    { 'nombre': 'Relleno con material propio o de banco del cuerpo de la subyacente',
      'predecesoras': 'K, L',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '3.000 días',
      'pesimista': '4 días' },

    { 'nombre': 'Compactación del cuerpo de la subyacente al 95%',
      'predecesoras': 'M',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.167 día',
      'pesimista': '2 días' },

    { 'nombre': 'Relleno con material propio o de banco del cuerpo de la subrasante',
      'predecesoras': 'M, N',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '3.000 días',
      'pesimista': '4 días' },

    { 'nombre': 'Compactación del cuerpo de la subrasante al 100%',
      'predecesoras': 'O',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.167 día',
      'pesimista': '2 días' },

    { 'nombre': 'Colocación de la sub-base con materiales granulares',
      'predecesoras': 'P',
      'optimo': '3 días',
      'real': '3 días',
      'estimado': '3.167 días',
      'pesimista': '4 días' },

    { 'nombre': 'Colocación de la base con materiales granulares',
      'predecesoras': 'K',
      'optimo': '3 días',
      'real': '4 días',
      'estimado': '3.833 días',
      'pesimista': '4 días' },

    { 'nombre': 'Colocación de asfalto tipo carretera',
      'predecesoras': 'R',
      'optimo': '3 días',
      'real': '4 días',
      'estimado': '4.167 días',
      'pesimista': '5 días' },

    { 'nombre': 'Excavación de zanjas para alcantarillado con zanjadora',
      'predecesoras': 'J,R',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.833 días',
      'pesimista': '3 días' },

    { 'nombre': 'Nivelación y compactación del fondo de la zanja con bailarina',
      'predecesoras': 'T',
      'optimo': '1 día',
      'real': '2 días',
      'estimado': '1.500 días',
      'pesimista': '3 días' },

    { 'nombre': 'Colocación del alcantarillado pluvial',
      'predecesoras': 'U',
      'optimo': '1 día',
      'real': '2 días',
      'estimado': '1.500 días',
      'pesimista': '3 días' },

    { 'nombre': 'Relleno y compactación de la zanja con bailarina',
      'predecesoras': 'V',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.000 día',
      'pesimista': '2 días' },

    { 'nombre': 'Cimbrado para banquetas',
      'predecesoras': 'W',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.667 días',
      'pesimista': '4 días' },

    { 'nombre': 'Armado para banquetas',
      'predecesoras': 'X',
      'optimo': '2 días',
      'real': '2 días',
      'estimado': '2.000 días',
      'pesimista': '3 días' },

    { 'nombre': 'Colado de concreto para banqueta y aliviadero',
      'predecesoras': 'Y',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.667 días',
      'pesimista': '4 días' },

    { 'nombre': 'Desimbrado de banqueta',
      'predecesoras': 'Z',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.000 día',
      'pesimista': '2 días' },

    { 'nombre': 'Excavación de cunetas con zanjadora pequeña',
      'predecesoras': 'T, 27',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.667 días',
      'pesimista': '4 días' },

    { 'nombre': 'Nivelación y compactación manual del fondo',
      'predecesoras': 'U,28',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.000 día',
      'pesimista': '2 días' },

    { 'nombre': 'Relleno de plantilla con material propio',
      'predecesoras': 'W,29',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.000 día',
      'pesimista': '2 días' },

    { 'nombre': 'Cimbrado para cunetas',
      'predecesoras': 'X,30',
      'optimo': '2 días',
      'real': '2 días',
      'estimado': '2.000 días',
      'pesimista': '3 días' },

    { 'nombre': 'Colado para cuneta manual',
      'predecesoras': 'Z,31',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.667 días',
      'pesimista': '4 días' },

    { 'nombre': 'Desimbrado de cunetas',
      'predecesoras': '27,32',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.000 día',
      'pesimista': '2 días' },

    { 'nombre': 'Cimbrado para columnas',
      'predecesoras': '31',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.667 días',
      'pesimista': '4 días' },

    { 'nombre': 'Armado de acero corrugado en forma circular',
      'predecesoras': '34',
      'optimo': '2 días',
      'real': '2 días',
      'estimado': '2.000 días',
      'pesimista': '3 días' },

    { 'nombre': 'Colado de concreto premezclado en columnas',
      'predecesoras': '35',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.667 días',
      'pesimista': '4 días' },

    { 'nombre': 'Colocacion de columnas prefabricadas',
      'predecesoras': '36',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.000 día',
      'pesimista': '2 días' },

    { 'nombre': 'Colocacion de vigas de acero para falso puente',
      'predecesoras': '37',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.000 día',
      'pesimista': '2 días' },

    { 'nombre': 'Colocacion de poste de acero para falso puente',
      'predecesoras': '37',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.000 día',
      'pesimista': '2 días' },

    { 'nombre': 'Cimbrado para losa puente',
      'predecesoras': '38,39',
      'optimo': '1 día',
      'real': '2 días',
      'estimado': '1.333 días',
      'pesimista': '3 días' },

    { 'nombre': 'Armado de acero corrugado para losa',
      'predecesoras': '40',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.500 días',
      'pesimista': '4 días' },

    { 'nombre': 'Colado de losa puente',
      'predecesoras': '41',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.667 días',
      'pesimista': '4 días' },

    { 'nombre': 'Colocacion de junta de dilatacion',
      'predecesoras': '41',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.667 días',
      'pesimista': '4 días' },
    
    { 'nombre': 'Colocacion de asfalto en losa puente',
      'predecesoras': '42,43',
      'optimo': '1 día',
      'real': '2 días',
      'estimado': '1.333 días',
      'pesimista': '3 días' },

    { 'nombre': 'Excavación para la losa de aproximación ',
      'predecesoras': '28',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.500 días',
      'pesimista': '4 días' },

    { 'nombre': 'Refine y nivelacion en la losa de aproximacion',
      'predecesoras': '45',
      'optimo': '3 días',
      'real': '4 días',
      'estimado': '3.500 días',
      'pesimista': '5 días' },

    { 'nombre': 'Transporte de material para terraplen',
      'predecesoras': '46',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.667 días',
      'pesimista': '4 días' },

    { 'nombre': 'Cimbrado de losa de aproximacion',
      'predecesoras': '34,47',
      'optimo': '2 días',
      'real': '2 días',
      'estimado': '2.000 días',
      'pesimista': '3 días' },

    { 'nombre': 'Armado con acero corrugado para la losa de aproximación ',
      'predecesoras': '48',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.000 día',
      'pesimista': '2 días' },
     
    { 'nombre': 'Colado de concreto para la losa de aproximación ',
      'predecesoras': '49',
      'optimo': '3 días',
      'real': '4 días',
      'estimado': '3.667 días',
      'pesimista': '5 días' },

    { 'nombre': 'Descimbrado de la losa de aproximacion',
      'predecesoras': '50',
      'optimo': '1 día',
      'real': '2 días',
      'estimado': '1.333 días',
      'pesimista': '3 días' },

    { 'nombre': 'Colocación de asfalto en losa de aproximación ',
      'predecesoras': '44,51',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.667 días',
      'pesimista': '4 días' },

    { 'nombre': 'Colocacion de tub PVC en puentes para drenaje',
      'predecesoras': '52',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.667 días',
      'pesimista': '4 días' },
    
    { 'nombre': 'Tub de fierro galvanizado de drenaje en losa de aproximacion',
      'predecesoras': '52',
      'optimo': '2 días',
      'real': '2 días',
      'estimado': '2.000 días',
      'pesimista': '3 días' },

    { 'nombre': 'Colocacion de apoyo movil de neopreno',
      'predecesoras': '53,54',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.667 días',
      'pesimista': '4 días' },

    { 'nombre': 'Colocacion de apoyo fijo de neopreno',
      'predecesoras': '55',
      'optimo': '1 día',
      'real': '2 días',
      'estimado': '1.333 días',
      'pesimista': '3 días' },
    
    { 'nombre': 'Colocacion de junta de dilatacion en losa de aproximacion',
      'predecesoras': '56',
      'optimo': '3 días',
      'real': '4 días',
      'estimado': '3.667 días',
      'pesimista': '5 días' },

    { 'nombre': 'Colocacion de barandas metalicas en losas puente',
      'predecesoras': '58',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.667 días',
      'pesimista': '4 días' },

    { 'nombre': 'Colocacion de barandas metalicas en losa de aproximacion',
      'predecesoras': '58',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.000 día',
      'pesimista': '2 días' },

    { 'nombre': 'Excavacion de tierra manual para postes de señalamiento',
      'predecesoras': '19',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.000 día',
      'pesimista': '2 días' },

    { 'nombre': 'Colocacion de concreto pobre para poste de señalamiento',
      'predecesoras': '61',
      'optimo': '2 días',
      'real': '2 días',
      'estimado': '2.000 días',
      'pesimista': '3 días' },

    { 'nombre': 'colocacion de poste de señalamiento',
      'predecesoras': '62',
      'optimo': '1 día',
      'real': '1 día',
      'estimado': '1.000 día',
      'pesimista': '2 días' },

    { 'nombre': 'Colocacion de poste de señalamiento en puentes',
      'predecesoras': '42,62',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.667 días',
      'pesimista': '4 días' },

    { 'nombre': 'Pintura y señalamiento en puentes',
      'predecesoras': '64',
      'optimo': '2 días',
      'real': '3 días',
      'estimado': '2.667 días',
      'pesimista': '4 días' },
      
  ];
    // Continúa en el siguiente bloque
  
  Widget itemActividad(Map<String, String> data) {
    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      elevation: 3,
      child: ExpansionTile(
        title: Text(
          data['nombre'] ?? '',
          style: const TextStyle(fontWeight: FontWeight.bold),
        ),
        children: [
          ListTile(
            title: const Text('Actividades Predecesoras'),
            trailing: Text(data['predecesoras'] ?? '-'),
          ),
          ListTile(
            title: const Text('Tiempo Óptimo'),
            trailing: Text(data['optimo'] ?? ''),
          ),
          ListTile(
            title: const Text('Tiempo Real'),
            trailing: Text(data['real'] ?? ''),
          ),
          ListTile(
            title: const Text('Tiempo Estimado'),
            trailing: Text(data['estimado'] ?? ''),
          ),
          ListTile(
            title: const Text('Tiempo Pesimista'),
            trailing: Text(data['pesimista'] ?? ''),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('PERTH - Actividades del Proyecto'),
        backgroundColor: Colors.deepPurple,
        centerTitle: true,
      ),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: actividades.map(itemActividad).toList(),
      ),
    );
  }
}